# Copyright 2021 Huawei Technologies Co., Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

base_config: ['../base/datasets/faster_rcnn_dataset.yaml',
              '../base/models/faster_rcnn_r50_fpn.yaml',
              '../base/schedules/schedule1x.yaml',
              '../base/base.yaml']
model:
  type: FasterRCNN
  backbone:
    type: VoVNet
    stem: [64, 64, 64]
    stage_conv_ch: [128, 160, 192, 224]
    stage_out_ch: [256, 512, 768, 1024]
    block_per_stage: [1, 3, 9, 3]
    layer_per_block: 5
    eSE: True
    dw: False
    input_ch: 3
    out_features: ['stage2', 'stage3', 'stage4', 'stage5']
    freeze_at: 0
    norm_bn: False
  neck:
    in_channels: [256, 512, 768, 1024]

train:
  backbone_path: "full path of model_zoo pretrained model file"
  max_epoch: 12
  ckpt_path: "outputs/"

eval:
  ckpt_path: ""
  ann_file: "datasets/coco/annotations/instances_val2017.json"
  test_batch_size: 2
  num_classes: 81